### ISSUE TITLE
Outbox uses old Mail gem

### ISSUE THREAD

**Issue by favour121** [localmed/outbox#1]
Is there any reason the Mail gem dependency hasn't been updated in over 2years?

OutBox currently forces users to downgrade Mail gem.

**Comment by thatgibbyguy** [comment]
@favour121 I have created a branch that updates the mail gem to 2.6 and will create a PR for @petebrowne to review. If you need to pull with the updated gem, please see https://github.com/thatgibbyguy/outbox/tree/update-mail-gem .

**Comment by petebrowne** [comment]
Cool I'll look over the PR - if tests pass, there's no reason to keep the mail gem at the current version

**Comment by petebrowne** [comment]
PR is merged in and `0.2.1` is pushed to rubygems. Thanks!
